--entrypoint for the game - if main.lua doesn't exist, the game won't run.
--automatically generated by lasspm

local lass = require("lass")

local scene = {}

function love.load()
	scene = lass.GameScene()
	scene:loadSettings("settings.lua")
	scene:load()
end

for i, f in ipairs({
	"draw",
	"update",
	"focus",
	"keypressed",
	"keyreleased",
	"mousefocus",
	"mousepressed",
	"mousereleased",
	"quit",
	"resize",
	"textinput",
	"threaderror",
	"visible"
}) do
	if f == "resize" then
		love[f] = function(...)
			scene.windowresize(scene, ...)
		end
	else
		love[f] = function(...)
			scene[f](scene, ...)
		end
	end
end
